config/routes.rb
Rails.application.routes.draw do
  resources :doctor_edu_articles
  resources :patients, :except => [:new]
  devise_for :doctors, :controllers => {:registrations => 'registrations'}

  get 'patients/index'
  get 'doctors/all_doctors'
  get 'doctors/all_articles'
  get 'doctors/home'
  # This route is for pass doctor id value to patients form implicitly
  get 'patients/new/:id', :to => 'patients#new', :as => 'new_patient'
  get 'doctors/show_doctor/:id', :to => 'doctors#show_doctor', :as => 'show_doctor'

  root 'doctors#home'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :length => { :in => 3..30}
  validates :designation, :length => { :in => 2..20}
  validates :email, :uniqueness => true

  has_many :patients, :dependent => :destroy
  has_many :doctor_edu_articles, :dependent => :destroy
  has_one_attached :image
  
end

app/models/doctor_edu_article.rb
class DoctorEduArticle < ApplicationRecord

  validates :about_article, :length => { minimum: 30}
  belongs_to :doctor
  has_one_attached :article
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :age, :inclusion => 1...100
  validates :name, :length => { :in => 3..30, :message => "The name is too small"}
  validates :phone, :uniqueness => { :scope => :doctor_id, :message => "This phone number is already taken" }
  
  belongs_to :doctor

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
end

app/controllers/doctor_edu_articles_controller.rb
class DoctorEduArticlesController < ApplicationController
  before_action :set_doctor_edu_article, :only => %i[ show edit update destroy ]

  # GET /doctor_edu_articles or /doctor_edu_articles.json
  def index
    @doctor_edu_articles = DoctorEduArticle.where(:doctor_id => current_doctor)
  end

  # GET /doctor_edu_articles/1 or /doctor_edu_articles/1.json
  def show
  end

  # GET /doctor_edu_articles/new
  def new
    @doctor_edu_article = DoctorEduArticle.new
  end

  # GET /doctor_edu_articles/1/edit
  # def edit
  # end

  # POST /doctor_edu_articles or /doctor_edu_articles.json
  def create
    @doctor_edu_article = DoctorEduArticle.new(doctor_edu_article_params)

    respond_to do |format|
      if @doctor_edu_article.save
        format.html { redirect_to @doctor_edu_article, :notice => "Doctor edu article was successfully created." }
        format.json { render :show, :status => :created, :location => @doctor_edu_article }
      else
        format.html { render :new, :status => :unprocessable_entity }
        format.json { render :json => @doctor_edu_article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_edu_articles/1 or /doctor_edu_articles/1.json
  # def update
  #   respond_to do |format|
  #     if @doctor_edu_article.update(doctor_edu_article_params)
  #       format.html { redirect_to @doctor_edu_article, notice: "Doctor edu article was successfully updated." }
  #       format.json { render :show, status: :ok, location: @doctor_edu_article }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @doctor_edu_article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /doctor_edu_articles/1 or /doctor_edu_articles/1.json
  def destroy
    @doctor_edu_article.destroy
    respond_to do |format|
      format.html { redirect_to doctor_edu_articles_url, :notice => "Doctor edu article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_edu_article
      @doctor_edu_article = DoctorEduArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_edu_article_params
      params.require(:doctor_edu_article).permit(:article_name, :about_article, :article, :doctor_id)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	def all_doctors

		@alldoctors = Doctor.all
		
	end

	def all_articles

		@allarticles = DoctorEduArticle.all
		
	end

	def show_doctor

		@showdoctor = Doctor.find(params[:id])
		
	end

	
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, :only => %i[ show edit update destroy ]
  before_action :ram, only: :index



  # GET /patients or /patients.json
  def index
    # order('oppointment_date ASC') is used for sort the data in Ascending order.
    # If you want to keep the data in decending order use DESC insted of ASC.
    # where(doctor_id: current_doctor) is used for retrive the prasent loged doctor's patients data.
    @patients = Patient.where(:doctor_id => current_doctor).
    where('oppointment_time BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day+100).
    order('oppointment_time ASC')

  end

  
  # GET /patients/new
  def new
    @patient = Patient.new
    @doc = Doctor.find(params[:id])

    #@doctors = Doctor.all
  end

  def ram

    p 'rammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm'
    
  end
  
  # def destroy
  #   @patient.destroy
  #   respond_to do |format|
  #     format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, :notice => "Patient was successfully created." }
        format.json { render :show, :status => :created, :location => @patient }
      else
        @doc = Doctor.find_by(:id => params[:patient][:doctor_id])
        format.html { render :new, :status => :unprocessable_entity }
        format.json { render :json => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
     
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age, :problem, :phone, :email, :doctor_id, :oppointment_time)
    end

  # # PATCH/PUT /patients/1 or /patients/1.json
  # def update
  #   respond_to do |format|
  #     if @patient.update(patient_params)
  #       format.html { redirect_to @patient, notice: "Patient was successfully updated." }
  #       format.json { render :show, status: :ok, location: @patient }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @patient.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	

   def sign_up_params
         params.require(:doctor).permit(:email, :password, :password_confirmation, :name, :designation, :image, :location)  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_edu_articles_helper.rb
module DoctorEduArticlesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/doctor_edu_articles/_form.html.erb
<%= form_with(model: doctor_edu_article, local: true) do |form| %>
  <% if doctor_edu_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor_edu_article.errors.count, "error") %> prohibited this doctor_edu_article from being saved:</h2>

      <ul>
        <% doctor_edu_article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <center>

  <br><br><br><br><h1>Upload Article</h1><br><br>

  <div class="form-outline mb-4">
    
    <%= form.text_field :article_name, required: true, style:"width:500px;", placeholder:'Enter Article Name', class:"form-control", autofocus: true %>
  </div>

  <div class="form-outline mb-4">
   
    <%= form.text_area :about_article, required: true, style:"width:500px;", placeholder:'Write Something related to the article', class:"form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.file_field :article, style:"width:500px;", placeholder:'Upload your article in pdf format', class:"form-control", required: true%>
    
  </div>


  <div class="field form-group">
    <!-- Has many articles with doctor. So we give doctor_id for linking. -->
    <!-- type: :hidden  is hide this input box to end user.-->
    <%= form.number_field :doctor_id, value: current_doctor.id, required: true, class:"form-control", type: :hidden%>
  
     
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class:"btn btn-primary", style:"width:200px;"%>
  </div>

  </center>
<% end %>

app/views/doctor_edu_articles/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Upload Article',  new_doctor_edu_article_path, class:'btn btn-warning mr-3', style:"float: right;"%>
<table align='center'>

<h1 align="center">My Articles</h1>
<% @doctor_edu_articles.each do |doctor_edu_article| %>
  
  <tr>
    
    <td>
      
      <div class="alert alert-primary mr-3 " role="alert" style="width: 500px; height: 100px;">
        <b>Article Name: </b><%= doctor_edu_article.article_name %><br>
        <b>About Article: </b><%= doctor_edu_article.about_article %><br><br>
      </div>

    </td>

       <td ><%= link_to 'Show', doctor_edu_article, class:"btn btn-outline-primary mr-3"%></td>
      
       <td>

        <%= link_to 'Destroy', doctor_edu_article, 
          class:"btn btn-outline-danger mr-3",
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
         
       </td>
   
  </tr>

   
<% end %>
</table> 

app/views/doctor_edu_articles/new.html.erb
<%= render 'form', doctor_edu_article: @doctor_edu_article %>

app/views/doctor_edu_articles/show.html.erb
<p id="notice"><%= notice %></p>

<center><iframe src="<%= rails_blob_path(@doctor_edu_article.article, disposition: :inline) %>" height="600" width="1000"></iframe></center>

app/views/doctors/all_articles.html.erb
<table align='center'>

	<tr><td align="center"><h1>Health Articles</h1></td></tr>
	<% @allarticles.each do |doctor_article| %>

	<tr> 
		<td>  
			<div class="alert alert-primary mr-3 " role="alert" style="width: 500px; height: 100px;">
				<b>Article Name: </b><%= doctor_article.article_name %><br>
				<b>About Article: </b><%= doctor_article.about_article %><br><br>

			</div>
		</td>
		<td ><%= link_to 'Show', doctor_article, class:"btn btn-outline-primary mr-3"%></td>  
	</tr>

	<% end %>
	
</table> 

app/views/doctors/all_doctors.html.erb
<%= stylesheet_link_tag "profile"%>

   
<div class="container">
  <div class="background">

    <div class='heading1'>
  
      <h4>AVAILABLE DOCTORS</h4>

    </div>
  
    <% @alldoctors.each do |doctor| %><br>
      <center>
        <div class="card-container">

          <div class="img">
            <%= image_tag(doctor.image, style:'width: 100%') if doctor.image.attached? %>
          </div>

          <h3><%= doctor.name %></h3>
          <h6><%= doctor.designation %></h6><br>
          <p><%= doctor.location %></p><br>
        
          <div class="buttons">
            <button class="primary">
              <%= link_to 'Show', show_doctor_path(doctor.id)%>
            </button>

            <button class="primary ghost">
              <%= link_to 'Contact', new_patient_path(doctor.id) %>
            </button>
          </div><br>

          <p><%= doctor.email %></p><br><br>
         <!-- <p><%= doctor.id %></p><br><br>
 -->
        </div>
       </center>
            
    <% end %>
  

<br>
  </div>
<br>
</div>

app/views/doctors/home.html.erb
<%= stylesheet_link_tag "profile"%>
<div class='backgroundimg'>

<% if notice %>
  <%= render 'layouts/alerts'%>
<% end -%>

<center><br><br><br><br><br><br>
<% if doctor_signed_in? %>


<p>Wellcome DR. <%= current_doctor.name%> </p>

<% if doctor_signed_in? %>
       
         <div class="blockquote">
          <%= link_to 'Appointments',  patients_path, class:"mb-0"%>
        </div>

      <% end %>


<% else %>
  <p> If you are a DOCTOR </p>
  <p>please create an account</p><br>
  <td class="text-nowrap">
 
      <%= link_to 'Sign up', new_doctor_registration_path, class:'btn btn-primary', style:"width:200px;"%>
 
      <%= link_to 'Sign in', new_doctor_session_path, class:'btn btn-outline-success', style:"width:200px;"%>

</div>
</div>

<% end %>

</center>
<br><br><br><br><br><br><br>

<% if doctor_signed_in? %>


<div class="secondbg">

	<br><h1 class="h2" align="center"> Write an Article</h1><br><br><br>


     <section class="section">
     <div class="row">
       <div class="col-sm-6 col-lg-6 col-md-6">
         <div class="box">
           <p class="blockquote mb-0">If you want to publish any articles as a doctor this is the best palce for you.
           Write an article and upload your article in pdf formate. Your all article will be displayed to all users of this organization.</p>
         </div>
       </div>
       <div class="col-sm-6 col-lg-6 col-md-6"  align="center">
         <div class="box  text-nowrap">
           <%= link_to 'Upload Article',  new_doctor_edu_article_path, class: 'btn btn-warning', style:"width:200px;"%>
            <%= link_to 'My aArticle',  doctor_edu_articles_path, class: 'btn btn-outline-secondary', style:"width:200px;"%>
         </div>
       </div> 
     </div>
    </section>

</div>
<% end -%>

app/views/doctors/show_doctor.html.erb
<br><br><table class="table table-striped table-bordered" style="width:980px;" align="center">

  <tr>
    <td>Doctor Name</td>
    <td><b><%= @showdoctor.name%></b></td>
  </tr>

  <tr>
    <td>Doctor Designation</td>
    <td><b><%= @showdoctor.designation %></b></td>
  </tr>

  <tr>
    <td>Doctor Location</td>
    <td><b><%= @showdoctor.location %></b></td>
  </tr>

  <tr>
    <td>Email</td>
    <td><b><%= @showdoctor.email %></b></td>
  </tr>

</table>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width:500px;" align="center">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark", style="background-color: #9400D3;">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">


    <%= image_tag "logo.png",style: 'height:70px;width:80px' %>

    <div class="nav-item active">
      <%= link_to 'Home',  doctors_home_path, class:'btn btn-outline-light mr-3'%>
    </div>

    <div class="nav-item active">
     <%= link_to 'Doctors',   doctors_all_doctors_path, class:'btn btn-outline-light mr-3'%>
   </div>

   <div class="nav-item active">
     <%= link_to 'Articles',   doctors_all_articles_path, class:'btn btn-outline-light mr-3'%>
   </div>

  </div>


 <% if doctor_signed_in? %>

 <div class="nav-item active">
  <%= link_to 'Profile', edit_doctor_registration_path, class:'btn btn-outline-light mr-3'%>
</div>
<div class="nav-item active">
  <%= link_to 'sign out', destroy_doctor_session_path, method: :delete, class:'btn btn-outline-warning mr-3'%>
</div>



<% end %>  

</div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="design.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title></title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <%= render 'layouts/header'%>

    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>


</html>

app/views/patients/_form.html.erb
<script type="text/javascript">
   
    $('.datepicker').datepicker({ 
        startDate: new Date()
    });
  
</script>

<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline mb-4">
    
    <%= form.text_field :name, style:"width:500px;", placeholder:'Enter Patient Name', class:"form-control"%>
  </div>

  <div class="form-outline mb-4">
    
    <%= form.number_field :age, style:"width:500px;", placeholder:'Enter Patient age', class:"form-control"%>
  </div>

  <div class="form-outline mb-4">
    
    <%= form.text_field :problem, style:"width:500px;", placeholder:'Enter Problem', class:"form-control"%>
  </div>

  <div class="form-outline mb-4">
   
    <%= form.text_field :phone, style:"width:500px;", placeholder:'Enter Phone Number', class:"form-control"%>
  </div>

  <div class="form-outline mb-4">
   
    <%= form.text_field :email, style:"width:500px;", placeholder:'Enter Email', class:"form-control"%>
  </div>


  <div class="form-outline mb-4">

    <%= form.text_field :doctor_id, value: @doc.id, style:"width:500px;", class:"form-control", type: :hidden%>

   
  </div>

 <div class='form-outline mb-4' id='datetimepickerDemo'>
  <%= form.datetime_field :oppointment_time, style:"width:500px;", class:"form-control datepicker"%>   
</div>

  <div class="actions">
    <%= form.submit 'Submit', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1 align="center">Patients</h1>

<table class="table" , style="width:1100px;" align="center">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Problem</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Appointment Date and Time</th>
      <!-- <th>Doctor</th> -->
      <!-- <th>Appointment Date</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.problem %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.email %></td>
         <td><%= patient.try(:oppointment_time).try(:strftime, ' %e / %B / %Y, Time:  %T') %></td>
       <!--  <td><%= patient.doctor_id %></td> -->
        <td><%#= patient.oppointment_date %></td>
        <td><%= link_to 'Show', patient %></td>
        <!-- <td><%#= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, :method => :delete, data: { confirm: 'Are you sure?' } %></td> --> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/patients/new.html.erb
<center>
<h1>Take Appointment</h1><br>
<%= render 'form', patient: @patient %>
</center>

<%#= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<br><br><table class="table table-striped table-bordered" style="width:980px;" align="center">

  <tr>
    <td>Patient Name</td>
    <td><b><%= @patient.name %></b></td>
  </tr>

  <tr>
    <td>Patient Age</td>
    <td><b><%= @patient.age %></b></td>
  </tr>

  <tr>
    <td>Problem</td>
    <td><b><%= @patient.problem %></b></td>
  </tr>

  <tr>
    <td>Contact Number</td>
    <td><b><%= @patient.phone %></b></td>
  </tr>

  <tr>
    <td>Email</td>
    <td><b><%= @patient.email %></b></td>
  </tr>

  <tr>
    <td>Appointment Date and Time</td>
    <td><b><%= @patient.try(:oppointment_time).try(:strftime, ' %e / %B / %Y, Time:  %T') %></b></td>
  </tr>

</table>